(()=>{'use strict';
const $=s=>document.querySelector(s),asset=p=>'assets/'+p,sk=location.pathname.includes('/sk/');
const canvas=$('#world'),ctx=canvas.getContext('2d'),I={},keys=new Set();let W=innerWidth,H=innerHeight,zoom=W<760?3.1:3.6,last=performance.now(),time=0,started=false,locked=false,view=null,card=0,dir=0,idle=0,moveX=0,moveY=0,teleport=null,menu=false;
const player={x:748,y:190},camera={x:740,y:700},visited=new Set();const mobile=/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent);if(mobile)document.body.classList.add('touch-device');
const places={about:{name:'About me',x:665,y:542},cv:{name:'Resume (CV)',x:330,y:1200},projects:{name:'Projects',x:842,y:880},technologies:{name:'Technologies',x:250,y:700},contact:{name:'Contact',x:1210,y:1460},memo0:{name:'Memo #1',x:1175,y:890},memo1:{name:'Memo #2',x:108,y:1450},memo2:{name:'Memo #3',x:1315,y:1170},memo3:{name:'Memo #4',x:1410,y:155},memo4:{name:'Memo #5',x:1210,y:455},memo5:{name:'Memo #6',x:345,y:140}};
const nav=[['about','About me'],['cv','CV'],['projects','Projects'],['technologies','Technologies'],['memo','#memo'],['contact','Contact']];
$('#desktop-nav').innerHTML=nav.map(([id,label])=>`<button data-page="${id}">${label}</button>`).join('');$('#menu').innerHTML=[...nav,['hood','Under the Hood']].map(([id,label])=>`<button data-page="${id}">${id==='cv'?'Resume (CV)':label}</button>`).join('')+'<a class="language" href="sk/">Slovensky</a>';
function resize(){W=innerWidth;H=innerHeight;canvas.width=W;canvas.height=H;zoom=W<760?3.1:3.6;ctx.imageSmoothingEnabled=false}resize();addEventListener('resize',resize);
const preload=['maps/big-map.webp','derived/world.webp','maps/exterior-small.webp','sprites/player.webp','sprites/player-sitting.webp','sprites/train.webp','sprites/duck.webp','sprites/npc-man.webp','sprites/npc-woman.webp','sprites/npc-man2.webp','sprites/npc-woman2.webp','sprites/waves.webp','sprites/windturbine.webp','sprites/cars/car1.webp'];
Promise.all(preload.map(p=>new Promise(resolve=>{let i=new Image;I[p]=i;i.onload=resolve;i.onerror=resolve;i.src=asset(p)}))).then(()=>{$('#loading').hidden=true;requestAnimationFrame(tick)});
function sprite(name,x,y,row=0,frame=0,scale=1){let im=I[name];if(!im?.naturalWidth)return;const fw=name==='sprites/duck.webp'?32:48,fh=fw,cols=Math.floor(im.width/fw),rows=Math.floor(im.height/fh);if(!cols||!rows)return;ctx.drawImage(im,(frame%cols)*fw,(row%rows)*fh,fw,fh,x-fw*scale/2,y-fh*scale*.8,fw*scale,fh*scale)}
function point(x,y){return {x:(x-camera.x)*zoom+W/2,y:(y-camera.y)*zoom+H/2}}
function pass(x,y){if(x<20||y<20||x>1580||y>1580)return false;return !!window.WALK_GRID?.[Math.floor(y/16)]?.[Math.floor(x/16)]}
function tick(now){const dt=Math.min(.05,(now-last)/1000);last=now;time+=dt;let vx=0,vy=0;if(started&&!locked&&!view&&!menu&&!(mobile&&W>H)){vx=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0)+moveX;vy=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0)+moveY;const n=Math.max(1,Math.hypot(vx,vy));vx/=n;vy/=n;if(vx||vy){idle=0;dir=Math.abs(vx)>Math.abs(vy)?(vx>0?3:2):(vy>0?0:1);let nx=player.x+vx*70*dt,ny=player.y+vy*70*dt;if(pass(nx,player.y))player.x=nx;if(pass(player.x,ny))player.y=ny;for(const [id,p] of Object.entries(places))if(Math.hypot(player.x-p.x,player.y-p.y)<12&&!visited.has(id)){go(id);break}}else idle+=dt;camera.x+=(player.x-camera.x)*Math.min(1,dt*6);camera.y+=(player.y-camera.y)*Math.min(1,dt*6)}
if(teleport){let t=Math.min(1,(time-teleport.start)/1.5),e=t*t*(3-2*t);camera.x=teleport.from.x+(teleport.to.x-teleport.from.x)*e;camera.y=teleport.from.y+(teleport.to.y-teleport.from.y)*e}
ctx.fillStyle='#387a4b';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-camera.x*zoom,H/2-camera.y*zoom);ctx.scale(zoom,zoom);ctx.imageSmoothingEnabled=false;let im=I['maps/big-map.webp'];if(im?.naturalWidth)ctx.drawImage(im,0,0,1600,1600);let detailed=I['derived/world.webp'];if(detailed?.naturalWidth){ctx.globalAlpha=.48;ctx.drawImage(detailed,0,0);ctx.globalAlpha=1}
// Moving residents follow local paths; no world screenshot is used as a background.
for(let j=0;j<18;j++){let bx=j<10?600+j*29:630+(j-10)*26,by=j<10?184+(j%3)*14:570+(j%4)*15;let walk=Math.sin(time*.3+j)*22;sprite(j%2?'sprites/npc-woman.webp':'sprites/npc-man.webp',bx+walk,by,walk>0?3:2,Math.floor(time*6+j),1)}
for(const [id,p] of Object.entries(places)){if(Math.abs(p.x-camera.x)>W/zoom||Math.abs(p.y-camera.y)>H/zoom)continue;ctx.fillStyle=visited.has(id)?'#ffeac9':id.startsWith('memo')?'#fb5674':'#ffb347';ctx.globalAlpha=.55+.25*Math.sin(time*4);ctx.beginPath();ctx.ellipse(p.x,p.y+5,13,6,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.font='5px Game';ctx.textAlign='center';ctx.fillStyle='white';ctx.fillText(p.name,p.x,p.y-37)}
for(let j=0;j<4;j++)sprite('sprites/duck.webp',620+(j%2)*210+Math.sin(time*.25+j)*20,660+Math.floor(j/2)*185+Math.cos(time*.3+j)*6,0,3+Math.floor(time*2)%6,.55);
let train=I['sprites/train.webp'];if(train?.naturalWidth){let tw=train.width,th=train.height;ctx.drawImage(train,0,0,tw,th,(time*25)%2300-650,244,tw*.8,th*.8)}
const car=I['sprites/cars/car1.webp'];if(car?.naturalWidth){for(let j=0;j<3;j++)ctx.drawImage(car,252,0,84,84,1040,300+(time*30+j*340)%1050,84,84)}
const rotor=I['sprites/windturbine.webp'];if(rotor?.naturalWidth){ctx.save();ctx.translate(360,1148);ctx.rotate(time*.6);ctx.drawImage(rotor,-55,-55,110,110);ctx.restore()}
const waves=I['sprites/waves.webp'];if(waves?.naturalWidth){ctx.globalAlpha=.3+.2*Math.sin(time*2);for(let j=0;j<22;j++){let x=590+(j%2)*220+(j*17%70),y=638+(j*19%95);ctx.drawImage(waves,x+Math.sin(time+j)*3,y,15,1.5)}ctx.globalAlpha=1}
for(let j=0;j<6;j++){ctx.fillStyle='rgba(235,235,224,.25)';ctx.fillRect(280+Math.sin(time+j)*8,720-((time*12+j*8)%65),6+j,6+j)}
if(started&&!teleport)sprite(idle>22?'sprites/player-sitting.webp':'sprites/player.webp',player.x,player.y,dir,(vx||vy)?Math.floor(time*8):0);ctx.restore();
if(locked){const p=point(player.x,player.y);ctx.save();ctx.globalCompositeOperation='lighter';for(let j=0;j<12;j++){ctx.fillStyle=j%2?'#72edff':'#fff4a2';ctx.fillRect(p.x+Math.sin(time*8+j)*30,p.y-j*7+Math.cos(time*5+j)*8,7,9)}ctx.restore()}
const mp=$('.mini-player');mp.style.left=(27+player.x/1600*50)+'%';mp.style.top=(19+player.y/1600*62)+'%';canvas.dataset.position=player.x.toFixed(1)+','+player.y.toFixed(1);canvas.dataset.camera=camera.x.toFixed(1)+','+camera.y.toFixed(1);requestAnimationFrame(tick)}
function close(){view=null;$('#overlay').hidden=true;$('#overlay').innerHTML='';$('#close').hidden=true;$('#hud').hidden=!started;keys.clear();moveX=moveY=0;$('#stick').style.transform='';}
function setMenu(on){menu=on;$('#menu').hidden=!on;document.body.classList.toggle('menu-open',on);$('#menu-toggle').textContent=on?'×':'Menu';$('#menu-toggle').setAttribute('aria-label',on?'Close menu':'Menu');moveX=moveY=0;keys.clear()}
async function go(id){if(locked)return;setMenu(false);close();if(id==='memo'||id==='hood'){show(id);return}let target=places[id];if(!target)return;locked=true;keys.clear();await new Promise(r=>setTimeout(r,350));teleport={from:{...camera},to:target,start:time};await new Promise(r=>setTimeout(r,1550));player.x=target.x;player.y=target.y;teleport=null;await new Promise(r=>setTimeout(r,450));locked=false;visited.add(id);show(id.startsWith('memo')?'card':id,id.startsWith('memo')?Number(id.slice(4)):0)}
$('#play').onclick=async()=>{if(started)return;started=true;locked=true;$('#entry').hidden=true;teleport={from:{...camera},to:player,start:time};await new Promise(r=>setTimeout(r,1550));teleport=null;locked=false;$('#hud').hidden=false};
$('#menu-toggle').onclick=()=>setMenu(!menu);$('#minimap').onclick=()=>show('map');$('#close').onclick=close;
document.addEventListener('click',e=>{let b=e.target.closest('[data-page],[data-action]');if(!b)return;if(b.dataset.page)go(b.dataset.page);else if(b.dataset.action==='map')show('map');else if(b.dataset.action==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{})}});
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)&&!view){e.preventDefault();keys.add(e.key)}});addEventListener('keyup',e=>keys.delete(e.key));addEventListener('blur',()=>{keys.clear();moveX=moveY=0});
let joyId=null;const joy=$('#joystick');joy.addEventListener('pointerdown',e=>{if(view||menu)return;joyId=e.pointerId;joy.setPointerCapture(joyId);drag(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)drag(e)});function drag(e){const r=joy.getBoundingClientRect();let x=e.clientX-r.x-r.width/2,y=e.clientY-r.y-r.height/2,m=Math.max(1,Math.hypot(x,y)/35);x/=m;y/=m;moveX=x/35;moveY=y/35;$('#stick').style.transform=`translate(${x}px,${y}px)`}function release(){joyId=null;moveX=moveY=0;$('#stick').style.transform=''}joy.addEventListener('pointerup',release);joy.addEventListener('pointercancel',release);
if(sk){document.documentElement.lang='sk';$('#play').textContent='Hraj';$('#shortcut').textContent='Nemáte čas na skúmanie môjho portfólia?';$('#rotate p').textContent='Otočte zariadenie';document.querySelectorAll('.language').forEach(a=>{a.href='index.html';a.textContent='EN'})}
function show(id,n=0){setMenu(false);view=id;card=n;$('#hud').hidden=true;$('#close').hidden=false;const layer=$('#overlay');layer.hidden=false;layer.className=id==='map'?'map-overlay':'';layer.innerHTML=render(id,n);layer.scrollTop=0;wire(id)}
const introAbout=["I'm Peter Oravec, a creative web developer with over 19 years of experience, based in Bratislava, Slovakia.","My work brings together Front-End development, JavaScript and Angular. With a background across the MEAN stack — MongoDB, Express, Angular and Node.js — I can connect an interface to the systems that make it work.","I enjoy building complex single-page applications and bringing visual ideas to life through animation and interaction. Understanding both design and software helps me bridge the space between a graphic concept, the browser and the backend. I care about how these parts work together, as well as the experience of the person using them.","Over the years, my work has grown from graphics and websites into full-stack products and Angular applications. I bring that experience to long-term software projects, turning ideas into clear, functional experiences."];
const jobs=[['2007','GAMO a.s.','gamo','IBM Lotus Notes developer, webdesigner','My career began with graphics, web design and IBM Lotus Notes development. Working on public-facing portals and business systems introduced me to the relationship between visual communication, structured information and reliable software.',['BBSK Portal','IRRR','SLEK','KVLSR','CRSZ','Kremnica Gags']],['2010','SCR','scr','Front-end developer, PHP developer','At SCR I developed websites and front-end experiences with PHP. The work covered media, communications and consumer brands, combining practical implementation with the demands of varied visual identities.',['TA3','Radio Express','SWAN','Energio','Gas Familia','Flatbook']],['2012','Kremsa Digital','kremsa','MEAN stack developer, Angular & Front-end developer, PHP & Wordpress developer','My work at Kremsa Digital expanded into full-stack products and Angular applications. Alongside client websites, I worked with databases, backend services and interfaces for connected business tools.',['Pioneer Projects CRM','SMBee']],['2018','Bethereum','bethereum','Angular & Front-end developer','At Bethereum I focused on Angular and front-end development, bringing interactive product interfaces and their underlying application logic together.',[]],['2020','VUB Bank Intesa Sanpaolo Group','vub','Angular & Front-end developer · Current position','I now work on banking applications and the automation of internal processes. This combines long-term Angular development with the practical need for clear workflows and dependable software.',[]]];
const projectLinks={'KVLSR':'https://www.kvlsr.sk/','CRSZ':'https://www.crsz.sk/','Kremnica Gags':'https://gagy.eu/','Gas Familia':'https://www.gasfamilia.com/','Flatbook':'https://flatbook.sk/'};
const projects=[['eUTxO.org','Visual Blockchain Explorer for Cardano','portfolio-eutxo.webp','Explore the structure of Cardano through a visual view of its blocks and UTXOs. The project connects blockchain data to an interactive interface, turning a complex network of relationships into something that can be explored.','Serverless Node.js · Google Firestore DB · BlockFrost API · PhaserJS · Tailwind CSS','https://eutxo.org/'],['Angular.sk','Free online course for Angular 2+','portfolio-angularsk.webp','A free video course introducing beginners to Angular. The material helps new developers work through the framework and start building their own applications.','Angular · Video course','https://angular.sk/'],['Peter Oravec portfolio v1','100% human-coded, no AI','peteroravec-v1.webp','An earlier portfolio written by hand, combining Angular, PhaserJS and a world created with Tiled. It explores how a game-like environment can become a personal website while keeping the underlying work focused on software and front-end development.','Angular · PhaserJS · Tiled','https://old.peteroravec.com/']];
const memos=[['100% Vibe coding',["AI can accelerate the journey from an idea to a working website. This portfolio explores that collaboration through a complete, interactive experience.","Speed is only one part of the process. The developer still supplies direction, decides what matters and connects individual pieces into a coherent product.","Context matters. A tool needs a clear understanding of the task and the surrounding code to make useful changes.","Generated code also needs judgment. Reviewing behavior, checking assumptions and refining details remain essential parts of development.","The interesting result is a collaboration: AI helps produce and explore possibilities, while a person evaluates and integrates them.","For me, the developer remains responsible for the final experience — how it looks, how it behaves and whether the parts actually work together."]],['Automatic testing',["Automated tests help move a project from code to dependable delivery. Browser tests check the paths a user actually follows, while API tests check the behavior behind the interface.","Midnight, Playwright and Puppeteer support browser automation; Mocha and Chai are useful parts of testing application logic. The value lies in checking meaningful behavior and catching failures before a release."]],['From Node.js logic to visual art in Canvas',["JavaScript connects very different kinds of work. It can organize backend logic in Node.js, support a browser interface and draw an animated visual world on a Canvas.","That connection makes it possible to move between structured software and creative expression without leaving the same language. Visual ideas become another way to explore what code can do."]],['Technologies I buried',["Every stage of a development career leaves useful experience behind. Older tools may no longer be part of everyday work, but the problems solved with them still shape how new systems are understood.","My focus today is JavaScript and the technologies around it. The earlier chapters remain part of that perspective, even as the tools change."]],['AI: Competitor or colleague?',["AI can produce code and offer alternatives quickly. Choosing the right alternative still requires an understanding of the purpose, the product and the tradeoffs.","I see the opportunity in collaboration: let the tool contribute, then use human judgment to review, refine and take responsibility for the outcome."]],["I'm not a game developer",["A game-like world is a creative way to present my work, but my professional focus is software development and long-term projects.","This portfolio brings visual experimentation and interactive interfaces together. The same curiosity informs the applications I build beyond this city."]]];
const hoodNames=['Architecture','Phaser.js','Chunk System','NPC System','Tiled Editor','Optimization'];
const hoodData=[['Architecture',["This portfolio combines an application interface with an explorable game world. Angular handles the interface, while Phaser renders and animates the environment behind it.","The city and its information panels play different roles. Navigation and content belong to the application, while the game handles the moving camera, characters and environment.","Keeping those responsibilities connected lets the portfolio respond as one experience: a destination in the city becomes a place to read about a project, a career or a technology."],null],['Phaser.js',["Phaser is a browser game framework for rendering interactive worlds with Canvas and WebGL. Here it supports the city, its characters and environmental animation.","A game scene brings together sprites, movement and camera behavior. Those systems give the portfolio a feeling of exploration beyond a conventional page.","The surrounding application presents readable information while the scene continues behind it."],null],['Chunk System',["A large world contains more detail than the user sees at any one time. Dividing it into chunks lets the renderer focus on the parts near the camera.","As the viewpoint changes, the relevant pieces of the city can be brought into active work while distant areas receive less attention.","Chunking and viewport culling help manage computation and keep a detailed environment practical in a browser."],'debug1.webp'],['NPC System',["The residents of the city move independently of the player. Their activity makes the environment feel inhabited rather than like a static illustration.","Movement needs to respect the surroundings and the role of each character. Paths, obstacles and the current viewpoint affect the work needed to update the scene.","The original technical overview describes using workers and selective updates to manage this ongoing computation."],'debug2.webp'],['Tiled Editor',["Tiled provides a visual way to organize a world from tiles. It turns individual artwork into the streets, buildings and landscape of a connected environment.","A map editor separates the arrangement of the city from the application interface. Layers and object placement help organize the scene for the game runtime.","The editor views illustrate the practical work of assembling the world and its areas of interaction."],'tiled1.webp'],['Optimization',["An animated city needs to balance visual detail with the work a browser can perform. Rendering only relevant areas is part of that balance.","Viewport culling and chunks reduce unnecessary drawing. Workers can handle suitable computations separately from the main interface.","Optimization supports the experience as a whole: readable content, responsive controls and a world that remains active behind the interface."],null]];
const paras=arr=>arr.map(p=>`<p>${p}</p>`).join('');const topButton='<button class="top-button" data-top aria-label="Scroll to top">Up ↑</button>';
function render(id,n){
if(id==='about')return `<article class="panel"><h1>About me</h1><div class="identity"><img src="${asset('images/peter-oravec.webp')}" alt="Peter Oravec"><div><strong>Peter Oravec</strong><small>Front-end & MEAN Stack developer</small></div><a class="linkedin-icon" href="https://www.linkedin.com/in/peteroravec" aria-label="LinkedIn" target="_blank" rel="noreferrer">in</a></div><h2>Bridging the Gap Between Design and Code</h2>${paras(introAbout)}</article>`;
if(id==='cv')return `<article class="panel wide"><h1>Curriculum Vitae</h1>${paras(['From graphics and web design to complex applications, my career has been a continuous exploration of how design and code work together.','Over the years I have worked across front-end and backend development, with a particular focus on JavaScript, Angular and the MEAN stack. That experience helps me understand an application as a whole, from its visual interface to its business logic.','Today, I apply that experience to banking workflows and process automation.'])}<div class="timeline">${jobs.map(([year,name,logo,role,body,items])=>`<section class="job"><div class="job-side"><span>${year}</span><img alt="${name}" src="${asset('images/logos/cv-'+logo+'.webp')}"></div><div><h2>${name}</h2><p class="muted">${role}</p><p>${body}</p>${items.length?`<details><summary aria-label="Show projects"></summary><h3>Selected projects</h3>${items.map(p=>`<p>${p}${projectLinks[p]?`<a href="${projectLinks[p]}" target="_blank" rel="noreferrer">Visit ↗</a>`:''}</p>`).join('')}${logo==='scr'?'<p>O2 · Sony · Pelikan · Corgoň · Zlatý Bažant · Heineken</p>':logo==='kremsa'?'<p>Pioneer Projects CRM: MongoDB, Node.js, Angular, ExpressJS.</p><p>SMBee: Node.js, MySQL, InfluxDB, Angular, Google Firebase, ExpressJS.</p><p>Legrand · Slovakia Chips · Karloff · Rajo · FONA · Amoeba · HB Reavis · Atheer Labs</p>':''}</details>`:''}</div></section>`).join('')}</div><p>Find me on <a href="https://www.linkedin.com/in/peteroravec">LinkedIn</a> to connect.</p>${topButton}</article>`;
if(id==='projects')return `<article class="panel"><h1>Projects</h1><p>Selected projects that bring together development, visual ideas and interactive experiences.</p></article>`+projects.map(([name,sub,img,body,tags,url])=>`<article class="panel project"><img src="${asset('images/portfolio/'+img)}" alt="${name}"><h2>${name}</h2><h3>${sub}</h3><p>${body}</p><p class="tags">${tags}</p><a class="visit" href="${url}" target="_blank" rel="noreferrer">Visit ↗</a></article>`).join('')+topButton;
if(id==='technologies')return `<article class="panel"><h1>Technologies</h1><p class="intro">The tools I use connect interfaces, application logic and backend services. JavaScript is the thread running through my work.</p>${[['Angular','angular','#b62432','Building complex single-page applications','Angular is a central part of my front-end work. It brings structure to complex applications and supports the interfaces, workflows and interactions that turn software into something useful.'],['Node.js','nodejs','#537d3b','JavaScript beyond the browser','Node.js lets me carry the same language into backend services. Together with databases and APIs, it supports the logic behind the interface and helps connect a product across its different layers.'],['Express.JS','expressjs','#34373d','Organizing backend applications','Express provides a practical foundation for organizing routes and backend behavior in Node.js. It is a familiar part of the MEAN stack and the applications I have built with it.'],['Javascript','javascript','#cfb826','A language for logic and creativity','JavaScript supports the everyday work of building web applications as well as visual experiments with Canvas and game frameworks. It connects the interactive browser experience to the systems behind it.']].map(([name,logo,bg,sub,p])=>`<section class="tech" style="background:${bg}"><img src="${asset('images/logos/dev-'+logo+'.webp')}" alt="${name}"><div><h2>${name}</h2><p>${sub}</p><p>${p}</p></div></section>`).join('')}<h2>Other technologies and experience</h2>${paras(['Automation via Puppeteer','Automated tests via Midnight, Playwright','MongoDB · HTML / CSS','Phaser.js — Canvas / WebGL game engine','Photoshop · MySQL · Google Firestore','Mockflow — wireframes'])}${topButton}</article>`;
if(id==='contact')return `<article class="panel contact"><h1>Contact</h1><p>Have a project in mind? Let's connect.</p><div class="contact-grid"><a href="https://www.linkedin.com/in/peteroravec" target="_blank" rel="noreferrer"><span class="icon">in</span><strong>LinkedIn</strong><span>linkedin.com/in/peteroravec</span></a><a href="mailto:p.oravec@gmail.com"><span class="icon">@</span><strong>Email</strong><span>p.oravec@gmail.com</span></a></div></article>`;
if(id==='memo')return `<article class="panel memo-directory"><h1>#memos</h1><div class="cards">${memos.map(([title],i)=>`<button data-page="memo${i}" aria-label="${title}"><img src="${asset('images/cards/card'+(i+1)+'_base.webp')}" alt="${title}"></button>`).join('')}</div></article>`;
if(id==='card')return `<article class="panel memo-detail"><div class="card-column"><div class="card-wrap"><div class="foil-card" role="button" tabindex="0" aria-label="Activate card effect"><img src="${asset('images/cards/card'+(n+1)+'_base.webp')}" alt="${memos[n][0]}"><img class="card-hint" src="${asset('images/ui/pointer-hand.webp')}" alt="Touch the card"></div></div><div class="card-nav">${n?`<button data-page="memo${n-1}" aria-label="Previous memo">‹</button>`:''}<button data-page="memo" aria-label="Memo directory">☰</button>${n<5?`<button data-page="memo${n+1}" aria-label="Next memo">›</button>`:''}</div></div><div class="memo-copy"><h1>${memos[n][0]}</h1>${paras(memos[n][1])}</div></article>`;
if(id==='hood')return `<article class="panel wide"><header class="hood-head"><h1>Under the Hood</h1><p>How does this portfolio work?</p></header><div class="hood-grid"><div class="hood-tabs">${hoodNames.map((x,i)=>`<button data-hood="${i}" class="${i?'':'selected'}">${x}</button>`).join('')}</div><div class="hood-content">${hoodHTML(0)}</div></div>${topButton}</article>`;
if(id==='map')return `<div class="monitor"><div class="map-screen"><img class="map-art" src="${asset('maps/big-map.webp')}" alt="Map of the city">${Object.entries(places).map(([k,p])=>`<button class="map-marker ${k.startsWith('memo')?'memo':''} ${visited.has(k)?'visited':''}" style="left:${p.x/16}%;top:${p.y/16}%" data-page="${k}" aria-label="Map ${p.name}">${p.name}</button>`).join('')}<span class="map-avatar" style="left:${player.x/16}%;top:${player.y/16}%"></span></div><div class="legend"><div><i></i>Info</div><div><i class="memo"></i>Memo</div><div><i class="visited"></i>Visited</div></div><img class="monitor-frame" src="${asset('images/ui/monitor.webp')}" alt="CRT monitor"></div>`;
return ''}
function hoodHTML(i){let [name,p,img]=hoodData[i];return `<h2>${name}</h2>${paras(p)}${i===1?'<a href="https://phaser.io/" target="_blank" rel="noreferrer">Visit Phaser.js ↗</a>':''}${img?`<img src="${asset('images/under-the-hood/'+img)}" alt="${name} illustration">`:''}`}
function wire(id){document.querySelectorAll('[data-top]').forEach(b=>b.onclick=()=>$('#overlay').scrollTo({top:0,behavior:'smooth'}));document.querySelectorAll('[data-hood]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-hood]').forEach(x=>x.classList.toggle('selected',x===b));$('.hood-content').innerHTML=hoodHTML(Number(b.dataset.hood))});document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>d.querySelector('summary').setAttribute('aria-label',d.open?'Hide projects':'Show projects')));let f=$('.foil-card');if(f){f.onclick=()=>f.classList.add('active');f.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();f.classList.add('active')}};f.onpointermove=e=>{const r=f.getBoundingClientRect(),x=(e.clientX-r.x)/r.width-.5,y=(e.clientY-r.y)/r.height-.5;f.style.transform=`rotateY(${x*25}deg) rotateX(${-y*18}deg)`;f.style.setProperty('--shine',((x+.5)*100)+'%')};f.onpointerleave=()=>f.style.transform=''}}

})();
